version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: flask_users_db
      POSTGRES_USER: flask_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flask_user -d flask_users_db"]
      interval: 5s
      retries: 5
      start_period: 10s

  test_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: flask_users_test_db
      POSTGRES_USER: flask_user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flask_user -d flask_users_test_db"]
      interval: 5s
      retries: 5
      start_period: 10s

  flask_app:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://flask_user:password@db/flask_users_db
      PYTHONPATH: /app
    ports:
      - "5000:5000"
    command: >
      sh -c "sleep 10 && python main.py"

  test_runner:
    build: .
    depends_on:
      test_db:
        condition: service_healthy
    environment:
      TEST_DATABASE_URL: postgresql://flask_user:password@test_db/flask_users_test_db
      PYTHONPATH: /app
    command: >
      sh -c "sleep 5 && pytest tests/"
    volumes:
      - .:/app

volumes:
  postgres_data:
  postgres_test_data:
